swift build
swift run LineChartSingleSeriesExample
swift run LineChartMultipleSeriesExample
swift run LineChartSubPlotHorizontallyStackedExample
swift run LineChartSubPlotVerticallyStackedExample
swift run LineChartSubPlotGridStackedExample
