#if !canImport(ObjectiveC)
import XCTest

extension AGGRendererTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AGGRendererTests = [
        ("testBase64Encoding", testBase64Encoding),
    ]
}

extension BarchartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BarchartTests = [
        ("testBarchart", testBarchart),
        ("testBarchartHatchedBackslash", testBarchartHatchedBackslash),
        ("testBarchartHatchedCross", testBarchartHatchedCross),
        ("testBarchartHatchedFilledCircle", testBarchartHatchedFilledCircle),
        ("testBarchartHatchedForwardSlash", testBarchartHatchedForwardSlash),
        ("testBarchartHatchedGrid", testBarchartHatchedGrid),
        ("testBarchartHatchedHollowCircle", testBarchartHatchedHollowCircle),
        ("testBarchartHatchedHorizontal", testBarchartHatchedHorizontal),
        ("testBarchartHatchedVertical", testBarchartHatchedVertical),
        ("testBarchartOrientationHorizontal", testBarchartOrientationHorizontal),
        ("testBarchartStackedHorizontal", testBarchartStackedHorizontal),
        ("testBarchartStackedVertical", testBarchartStackedVertical),
    ]
}

extension HistogramTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HistogramTests = [
        ("testHistogram", testHistogram),
        ("testHistogramMultiStacked", testHistogramMultiStacked),
        ("testHistogramMultiStackedColorBleed", testHistogramMultiStackedColorBleed),
        ("testHistogramMultiStackedStep", testHistogramMultiStackedStep),
        ("testHistogramStacked", testHistogramStacked),
        ("testHistogramStackedStep", testHistogramStackedStep),
        ("testHistogramStackedStepLineJoins", testHistogramStackedStepLineJoins),
        ("testHistogramStackedStepOffset", testHistogramStackedStepOffset),
        ("testHistogramStep", testHistogramStep),
    ]
}

extension LineChartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LineChartTests = [
        ("testLineChartFunctionPlot", testLineChartFunctionPlot),
        ("testLineChartMultipleSeries", testLineChartMultipleSeries),
        ("testLineChartSecondaryAxis", testLineChartSecondaryAxis),
        ("testLineChartSingleSeries", testLineChartSingleSeries),
        ("testLineChartSubplotGridStacked", testLineChartSubplotGridStacked),
        ("testLineChartSubplotHorizontallyStacked", testLineChartSubplotHorizontallyStacked),
        ("testLineChartSubplotVerticallyStacked", testLineChartSubplotVerticallyStacked),
    ]
}

extension ScatterPlotTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScatterPlotTests = [
        ("testScatterPlot", testScatterPlot),
    ]
}

extension SubPlotTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubPlotTests = [
        ("testNestedSubplots", testNestedSubplots),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AGGRendererTests.__allTests__AGGRendererTests),
        testCase(BarchartTests.__allTests__BarchartTests),
        testCase(HistogramTests.__allTests__HistogramTests),
        testCase(LineChartTests.__allTests__LineChartTests),
        testCase(ScatterPlotTests.__allTests__ScatterPlotTests),
        testCase(SubPlotTests.__allTests__SubPlotTests),
    ]
}
#endif
