name: SwiftPlot Ubuntu

on:
  push:
    branches: master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Freetype
      run: sudo apt-get install libfreetype6-dev
    - name: Install Swift Dependencies
      run: sudo apt-get install clang libicu-dev
    - name: Install Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: "5.4"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Upload test artefacts
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: images
        path: ./output
